- hosts: netbox
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: 00-dnf-prep.yml
    - import_tasks: 01-luks-prep.yml
    - import_tasks: 02-packages.yml
    - import_tasks: 03-netbox-user.yml
    - import_tasks: 04-postgresql.yml
    - import_tasks: 05-redis.yml
    - import_tasks: 06-netbox.yml
    - import_tasks: 07-netbox-utils.yml
    - import_tasks: 08-apache.yml
    - import_tasks: 99-finalize.yml
